table = [
        "Name:", 
        "Symbol",
        "Atomic Number",
        "Atomic Weight (u.m)",
        "Density (g/cm³)",
        "Melting Point (K)",
        "Boiling Point (K)",
        "Atomic Radius (pm)",
        "Covalent Radius (pm)",
        "Ionic Radius (pm)",
        "Atomic Volume (cm³/mol)",
        "Specific Heat (@20°C J/(K*mol))",
        "Fusion Heat (kJ/mol)",
        "Evaporation Heat (kJ/mol)",
        "Thermal Conductivity (@25°C W/(m*K))",
        "Debye temperature (K)",
        "Pauling Negativity Number",
        "First Ionizing Energy (kJ/mol)",
        "Oxidation states",
        "Electronic Configuration",
        "Lattice structure",
        "Lattice constant (Å)",
        "Lattice c/a ratio",
        "Appearance",
        "Discovery date",
        "Discovered by",
        "Named after"]

property_lst =[
["Hydrogen", "H",
         "1",
         "1.00794",
         "0.0708 (@ -253°C)",
         "14.01",
        "20.28",
         "53-79",
         "32",
         "54 (-1e)",
         "14.1",
         "0.904 (H-H)",
         "0.117 (H-H)",
         "0.1815",
         "110.00",
         "2.20",
         "1311.3",
         "1, 0, -1",
         "1s¹",
         "HEX",
         "3.750",
         "1.731",
         "Colorless, odorless, tasteless gas",
         "1766 (England)",
         "Henry Cavendish",
         "Greek: hydro (water) and genes (generate)",
         "n/a"],
["Helium",
        "He",
        "2",
        "4.002602",
        "0.147 (@ -270°C)",
    "0.95",
    "4.216",
    "28-31",
    "28-140",
    "93",
    "31.8",
    "5.188",
    "n/a",
    "0.08",
    "0.152",
    "n/a",
    "4.5",
    "2361.3",
    "0",
    "1s²",
    "HEX",
    "3.570",
    "1.633",
    "Inert, colorless, odorless, tasteless gas",
    "1895 (Scotland/Sweden)",
    "Sir William Ramsey, Nils Langet, P.T.Cleve",
    "Greek: helios (sun)"
    ]]